---
fw_ports:
  - 6443/tcp          # API server
  - 2379-2380/tcp     # etcd
  - 10250/tcp         # kubelet
  - 10257/tcp         # controller manager
  - 10259/tcp         # scheduler
  - 8472/udp          # VXLAN de Flannel
